#!/bin/env python

import numpy as np
import pandas as pd
data = {
        'A' : [1, 2, 9, 4, 0],
        'B' : [9, 4, 8, 2, 0],
        'C' : [1, 3, 7, 3, 1],
        }

frame = pd.DataFrame(data)

print(frame)

print("\ncorr:\n")
print(frame.corr())
print(frame.corr(method='spearman'))
print(frame.corr(method='kendall'))

# 参考：  https://baijiahao.baidu.com/s?id=1684531657686987772&wfr=spider&for=pc
